datasets:
  llava_instruct_156k:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /export/dataset/llava_instruct/llava_instruction_156k.json
          storage: dataset/llava_instruct/llava_instruction_156k.json
      images:
          storage: dataset/llava_instruct/coco/train2017
